<?php

return [
    'SITE_NAME' => 'Akisitonoma',
    'BASE_URL' => 'http://localhost:8000',
    'ADMIN_EMAIL' => 'TODO_ADMIN_EMAIL',
    'APP_TIMEZONE' => 'TODO_TIMEZONE',
    'DATABASE_PATH' => dirname(__DIR__) . '/storage/database.sqlite',
    'SMTP_HOST' => 'TODO_SMTP_HOST',
    'SMTP_PORT' => 587,
    'SMTP_USERNAME' => 'TODO_SMTP_USERNAME',
    'SMTP_PASSWORD' => 'TODO_SMTP_PASSWORD',
    'SMTP_FROM_EMAIL' => 'TODO_SMTP_FROM_EMAIL',
    'SMTP_FROM_NAME' => 'Akisitonoma',
    'GOOGLE_MAPS_API_KEY' => 'TODO_GOOGLE_MAPS_API_KEY',
    'PICKUP_INSTRUCTIONS' => 'TODO_PICKUP_INSTRUCTIONS',
    'DELIVERY_INSTRUCTIONS' => 'TODO_DELIVERY_INSTRUCTIONS',
];
